apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-news-deployment
spec:
  template:
    metadata:
      name: portal-news
      labels:
        app: portal-news
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-config-map
  selector:
    matchLabels:
      app: portal-news
  replicas: 3

 