apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: system-news-statefulset
spec:
  selector:
    matchLabels:
      app: system-news
  serviceName: svc-system-news
  replicas: 2
  template:
    metadata:
      labels:
        app: system-news
    spec:
      containers:
      - name: system-news
        image: aluracursos/sistema-noticias:1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: system-news-config-map
        volumeMounts:
        - name: imagens
          mountPath: /var/www/html/uploads
        - name: sessao
          mountPath: tmp/
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30 
            failureThreshold: 3
        rednessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30 
            failureThreshold: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
